version: "3.8"

services:
  smileornot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7860:7860"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
